package uy.gub.hcen.clinic.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.util.Objects;

/**
 * Clinic Entity (PostgreSQL)
 *
 * Represents a healthcare facility integrated with the HCEN (Historia Clínica Electrónica Nacional).
 * Each clinic has a peripheral node that communicates with the central HCEN component to register
 * users and clinical documents.
 *
 * Database: PostgreSQL
 * Schema: clinics
 * Table: clinics
 *
 * Integration Points:
 * - Peripheral Node URL: API endpoint for the clinic's peripheral component
 * - API Key: Secure authentication token for central ↔ peripheral communication
 * - Status: Tracks onboarding and operational status
 *
 * Business Rules:
 * - Clinic IDs must be unique and immutable
 * - API keys will be encrypted/hashed in future versions
 * - Status transitions: PENDING_ONBOARDING → ACTIVE → INACTIVE
 * - Only ACTIVE clinics can register users and documents
 *
 * @author TSE 2025 Group 9
 * @version 1.0
 * @since 2025-10-17
 */
@Entity
@Table(name = "clinics", schema = "clinics",
       indexes = {
           @Index(name = "idx_clinics_status", columnList = "status"),
           @Index(name = "idx_clinics_city", columnList = "city")
       })
public class Clinic {

    /**
     * Unique clinic identifier (generated by HCEN Admin)
     * Format: clinic-{uuid} or custom identifier
     */
    @Id
    @Column(name = "clinic_id", length = 50, nullable = false)
    private String clinicId;

    /**
     * Official name of the clinic or healthcare facility
     */
    @Column(name = "clinic_name", length = 200, nullable = false)
    private String clinicName;

    /**
     * Physical address of the clinic
     */
    @Column(name = "address", length = 300)
    private String address;

    /**
     * City where the clinic is located
     */
    @Column(name = "city", length = 100)
    private String city;

    /**
     * Contact phone number
     */
    @Column(name = "phone_number", length = 20)
    private String phoneNumber;

    /**
     * Contact email address
     */
    @Column(name = "email", length = 255)
    private String email;

    /**
     * URL of the clinic's peripheral node API endpoint
     * Format: https://clinic-name.hcen.uy/api
     */
    @Column(name = "peripheral_node_url", length = 500)
    private String peripheralNodeUrl;

    /**
     * API key for secure communication between central and peripheral components
     * Note: Will be encrypted/hashed in future versions (security requirement)
     */
    @Column(name = "api_key", length = 100)
    private String apiKey;

    /**
     * Current operational status of the clinic
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", length = 20, nullable = false)
    private ClinicStatus status;

    /**
     * Timestamp when the clinic was successfully onboarded
     * Populated when status transitions to ACTIVE
     */
    @Column(name = "onboarded_at")
    private LocalDateTime onboardedAt;

    /**
     * Timestamp of clinic registration (auto-populated)
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Clinic status enumeration
     * Defines the operational state of a clinic in the HCEN system
     */
    public enum ClinicStatus {
        /**
         * Clinic is registered but onboarding is not complete
         * Cannot register users or documents in this state
         */
        PENDING_ONBOARDING,

        /**
         * Clinic is fully onboarded and operational
         * Can register users and documents
         */
        ACTIVE,

        /**
         * Clinic is temporarily or permanently deactivated
         * Cannot register users or documents in this state
         */
        INACTIVE
    }

    /**
     * Default constructor (required by JPA)
     */
    public Clinic() {
        this.status = ClinicStatus.PENDING_ONBOARDING;
    }

    /**
     * Full constructor for creating new clinics
     *
     * @param clinicId Unique clinic identifier
     * @param clinicName Official clinic name
     * @param address Physical address
     * @param city City location
     * @param phoneNumber Contact phone
     * @param email Contact email
     * @param peripheralNodeUrl Peripheral node API URL
     * @param apiKey API authentication key
     */
    public Clinic(String clinicId, String clinicName, String address, String city,
                  String phoneNumber, String email, String peripheralNodeUrl, String apiKey) {
        this.clinicId = clinicId;
        this.clinicName = clinicName;
        this.address = address;
        this.city = city;
        this.phoneNumber = phoneNumber;
        this.email = email;
        this.peripheralNodeUrl = peripheralNodeUrl;
        this.apiKey = apiKey;
        this.status = ClinicStatus.PENDING_ONBOARDING;
    }

    /**
     * JPA lifecycle callback - set creation timestamp before persist
     */
    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
    }

    /**
     * Activates the clinic after successful onboarding
     */
    public void activate() {
        this.status = ClinicStatus.ACTIVE;
        if (this.onboardedAt == null) {
            this.onboardedAt = LocalDateTime.now();
        }
    }

    /**
     * Deactivates the clinic
     */
    public void deactivate() {
        this.status = ClinicStatus.INACTIVE;
    }

    /**
     * Checks if the clinic is active and operational
     *
     * @return true if status is ACTIVE, false otherwise
     */
    public boolean isActive() {
        return this.status == ClinicStatus.ACTIVE;
    }

    // Getters and Setters

    public String getClinicId() {
        return clinicId;
    }

    public void setClinicId(String clinicId) {
        this.clinicId = clinicId;
    }

    public String getClinicName() {
        return clinicName;
    }

    public void setClinicName(String clinicName) {
        this.clinicName = clinicName;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPeripheralNodeUrl() {
        return peripheralNodeUrl;
    }

    public void setPeripheralNodeUrl(String peripheralNodeUrl) {
        this.peripheralNodeUrl = peripheralNodeUrl;
    }

    public String getApiKey() {
        return apiKey;
    }

    public void setApiKey(String apiKey) {
        this.apiKey = apiKey;
    }

    public ClinicStatus getStatus() {
        return status;
    }

    public void setStatus(ClinicStatus status) {
        this.status = status;
    }

    public LocalDateTime getOnboardedAt() {
        return onboardedAt;
    }

    public void setOnboardedAt(LocalDateTime onboardedAt) {
        this.onboardedAt = onboardedAt;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    // Equals, HashCode, and ToString

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Clinic clinic = (Clinic) o;
        return Objects.equals(clinicId, clinic.clinicId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(clinicId);
    }

    @Override
    public String toString() {
        return "Clinic{" +
               "clinicId='" + clinicId + '\'' +
               ", clinicName='" + clinicName + '\'' +
               ", city='" + city + '\'' +
               ", status=" + status +
               ", createdAt=" + createdAt +
               '}';
    }
}
