-- ================================================================
-- HCEN - Clinics Schema
-- ================================================================
-- Description: Registry of clinics and healthcare facilities integrated with HCEN
-- Version: V005
-- Author: TSE 2025 Group 9
-- ================================================================

-- Create Clinics schema if not exists
CREATE SCHEMA IF NOT EXISTS clinics;

-- Create clinics table
CREATE TABLE IF NOT EXISTS clinics.clinics (
    -- Primary identification
    clinic_id VARCHAR(50) PRIMARY KEY,

    -- Clinic information
    clinic_name VARCHAR(200) NOT NULL,
    address VARCHAR(300),
    city VARCHAR(100),
    phone_number VARCHAR(20),
    email VARCHAR(255),

    -- Integration configuration
    peripheral_node_url VARCHAR(500),
    api_key VARCHAR(100),

    -- Clinic status with constraint
    status VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE', 'PENDING_ONBOARDING')),

    -- Audit timestamps
    onboarded_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for performance optimization
CREATE INDEX IF NOT EXISTS idx_clinics_status ON clinics.clinics(status);
CREATE INDEX IF NOT EXISTS idx_clinics_city ON clinics.clinics(city);
CREATE INDEX IF NOT EXISTS idx_clinics_created_at ON clinics.clinics(created_at);

-- Add comments for documentation
COMMENT ON SCHEMA clinics IS 'Registry of clinics and healthcare facilities integrated with HCEN';
COMMENT ON TABLE clinics.clinics IS 'Central registry of all clinics integrated with the national health system';
COMMENT ON COLUMN clinics.clinics.clinic_id IS 'Unique clinic identifier (generated by HCEN)';
COMMENT ON COLUMN clinics.clinics.clinic_name IS 'Official name of the clinic or healthcare facility';
COMMENT ON COLUMN clinics.clinics.peripheral_node_url IS 'URL of the clinic''s peripheral node API endpoint';
COMMENT ON COLUMN clinics.clinics.api_key IS 'API key for secure communication between central and peripheral components';
COMMENT ON COLUMN clinics.clinics.status IS 'Clinic status: ACTIVE, INACTIVE, or PENDING_ONBOARDING';
COMMENT ON COLUMN clinics.clinics.onboarded_at IS 'Timestamp when the clinic was successfully onboarded';
COMMENT ON COLUMN clinics.clinics.created_at IS 'Timestamp of clinic registration';
