package uy.gub.hcen.rndc.entity;

/**
 * Document Type Enumeration
 *
 * Defines the types of clinical documents that can be registered in the RNDC.
 * These types correspond to standard medical documentation used in Uruguay's
 * healthcare system.
 *
 * <p>Each document type has specific characteristics and is used for different
 * clinical purposes. The RNDC uses this classification for:
 * <ul>
 *   <li>Document indexing and search</li>
 *   <li>Access policy enforcement (e.g., only cardiologists can access certain types)</li>
 *   <li>Analytics and reporting</li>
 * </ul>
 *
 * @author TSE 2025 Group 9
 * @version 1.0
 * @since 2025-10-17
 */
public enum DocumentType {

    /**
     * Clinical notes written by healthcare professionals during patient consultations
     */
    CLINICAL_NOTE("Clinical Note"),

    /**
     * Laboratory test results (blood work, urinalysis, etc.)
     */
    LAB_RESULT("Laboratory Result"),

    /**
     * Medical imaging reports (X-rays, CT scans, MRI, ultrasound, etc.)
     */
    IMAGING("Medical Imaging"),

    /**
     * Prescription documents for medications
     */
    PRESCRIPTION("Prescription"),

    /**
     * Hospital discharge summaries
     */
    DISCHARGE_SUMMARY("Discharge Summary"),

    /**
     * Vaccination records and immunization history
     */
    VACCINATION_RECORD("Vaccination Record"),

    /**
     * Surgical operation reports
     */
    SURGICAL_REPORT("Surgical Report"),

    /**
     * Pathology and histopathology reports
     */
    PATHOLOGY_REPORT("Pathology Report"),

    /**
     * General medical consultations
     */
    CONSULTATION("Consultation"),

    /**
     * Emergency department reports
     */
    EMERGENCY_REPORT("Emergency Report"),

    /**
     * Referrals to specialists or other healthcare providers
     */
    REFERRAL("Referral"),

    /**
     * Progress notes documenting patient's clinical progress
     */
    PROGRESS_NOTE("Progress Note"),

    /**
     * Allergy and adverse reaction records
     */
    ALLERGY_RECORD("Allergy Record"),

    /**
     * Vital signs measurements (blood pressure, temperature, etc.)
     */
    VITAL_SIGNS("Vital Signs"),

    /**
     * Diagnostic reports (ECG, EEG, etc.)
     */
    DIAGNOSTIC_REPORT("Diagnostic Report"),

    /**
     * Treatment plans and care plans
     */
    TREATMENT_PLAN("Treatment Plan"),

    /**
     * Informed consent documents
     */
    INFORMED_CONSENT("Informed Consent"),

    /**
     * Other document types not covered by specific categories
     */
    OTHER("Other");

    private final String displayName;

    /**
     * Constructor
     *
     * @param displayName Human-readable display name for this document type
     */
    DocumentType(String displayName) {
        this.displayName = displayName;
    }

    /**
     * Gets the human-readable display name
     *
     * @return Display name for UI presentation
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Checks if this document type contains sensitive information
     * that requires higher access restrictions
     *
     * @return true if this is a sensitive document type
     */
    public boolean isSensitive() {
        return this == PATHOLOGY_REPORT ||
               this == SURGICAL_REPORT ||
               this == EMERGENCY_REPORT ||
               this == ALLERGY_RECORD;
    }

    /**
     * Checks if this document type is typically generated by laboratories
     *
     * @return true if this is a laboratory document
     */
    public boolean isLabDocument() {
        return this == LAB_RESULT ||
               this == PATHOLOGY_REPORT;
    }

    /**
     * Checks if this document type is related to imaging
     *
     * @return true if this is an imaging document
     */
    public boolean isImagingDocument() {
        return this == IMAGING ||
               this == DIAGNOSTIC_REPORT;
    }

    @Override
    public String toString() {
        return displayName;
    }
}
